package crm

type CompanyProperties struct {
	AboutUs                                                               string  `json:"about_us,omitempty"`
	ClosedateTimestampEarliestValueA2a17e6e                               string  `json:"closedate_timestamp_earliest_value_a2a17e6e,omitempty"`
	Cohort                                                                string  `json:"cohort,omitempty"`
	DealByCompany                                                         string  `json:"deal_by_company,omitempty"`
	Facebookfans                                                          int64   `json:"facebookfans,omitempty"`
	FirstContactCreatedateTimestampEarliestValue78b50eea                  string  `json:"first_contact_createdate_timestamp_earliest_value_78b50eea,omitempty"`
	FirstConversionDate                                                   string  `json:"first_conversion_date,omitempty"`
	FirstConversionDateTimestampEarliestValue61f58f2c                     string  `json:"first_conversion_date_timestamp_earliest_value_61f58f2c,omitempty"`
	FirstConversionEventName                                              string  `json:"first_conversion_event_name,omitempty"`
	FirstConversionEventNameTimestampEarliestValue68ddae0a                string  `json:"first_conversion_event_name_timestamp_earliest_value_68ddae0a,omitempty"`
	FirstDealCreatedDate                                                  string  `json:"first_deal_created_date,omitempty"`
	FoundedYear                                                           string  `json:"founded_year,omitempty"`
	HsAdditionalDomains                                                   string  `json:"hs_additional_domains,omitempty"`
	HsAllAssignedBusinessUnitIds                                          string  `json:"hs_all_assigned_business_unit_ids,omitempty"`
	HsAnalyticsFirstTimestamp                                             string  `json:"hs_analytics_first_timestamp,omitempty"`
	HsAnalyticsFirstTimestampTimestampEarliestValue11e3a63a               string  `json:"hs_analytics_first_timestamp_timestamp_earliest_value_11e3a63a,omitempty"`
	HsAnalyticsFirstTouchConvertingCampaign                               string  `json:"hs_analytics_first_touch_converting_campaign,omitempty"`
	HsAnalyticsFirstTouchConvertingCampaignTimestampEarliestValue4757fe10 string  `json:"hs_analytics_first_touch_converting_campaign_timestamp_earliest_value_4757fe10,omitempty"`
	HsAnalyticsFirstVisitTimestamp                                        string  `json:"hs_analytics_first_visit_timestamp,omitempty"`
	HsAnalyticsFirstVisitTimestampTimestampEarliestValueAccc17ae          string  `json:"hs_analytics_first_visit_timestamp_timestamp_earliest_value_accc17ae,omitempty"`
	HsAnalyticsLastTimestamp                                              string  `json:"hs_analytics_last_timestamp,omitempty"`
	HsAnalyticsLastTimestampTimestampLatestValue4e16365a                  string  `json:"hs_analytics_last_timestamp_timestamp_latest_value_4e16365a,omitempty"`
	HsAnalyticsLastTouchConvertingCampaign                                string  `json:"hs_analytics_last_touch_converting_campaign,omitempty"`
	HsAnalyticsLastTouchConvertingCampaignTimestampLatestValue81a64e30    string  `json:"hs_analytics_last_touch_converting_campaign_timestamp_latest_value_81a64e30,omitempty"`
	HsAnalyticsLastVisitTimestamp                                         string  `json:"hs_analytics_last_visit_timestamp,omitempty"`
	HsAnalyticsLastVisitTimestampTimestampLatestValue999a0fce             string  `json:"hs_analytics_last_visit_timestamp_timestamp_latest_value_999a0fce,omitempty"`
	HsAnalyticsLatestSource                                               string  `json:"hs_analytics_latest_source,omitempty"`
	HsAnalyticsLatestSourceData1                                          string  `json:"hs_analytics_latest_source_data_1,omitempty"`
	HsAnalyticsLatestSourceData2                                          string  `json:"hs_analytics_latest_source_data_2,omitempty"`
	HsAnalyticsLatestSourceTimestamp                                      string  `json:"hs_analytics_latest_source_timestamp,omitempty"`
	HsAnalyticsNumPageViews                                               int64   `json:"hs_analytics_num_page_views,omitempty"`
	HsAnalyticsNumPageViewsCardinalitySumE46e85b0                         int64   `json:"hs_analytics_num_page_views_cardinality_sum_e46e85b0,omitempty"`
	HsAnalyticsNumVisits                                                  int64   `json:"hs_analytics_num_visits,omitempty"`
	HsAnalyticsNumVisitsCardinalitySum53d952a6                            int64   `json:"hs_analytics_num_visits_cardinality_sum_53d952a6,omitempty"`
	HsAnalyticsSource                                                     string  `json:"hs_analytics_source,omitempty"`
	HsAnalyticsSourceData1                                                string  `json:"hs_analytics_source_data_1,omitempty"`
	HsAnalyticsSourceData1TimestampEarliestValue9b2f1fa1                  string  `json:"hs_analytics_source_data_1_timestamp_earliest_value_9b2f1fa1,omitempty"`
	HsAnalyticsSourceData2                                                string  `json:"hs_analytics_source_data_2,omitempty"`
	HsAnalyticsSourceData2TimestampEarliestValue9b2f9400                  string  `json:"hs_analytics_source_data_2_timestamp_earliest_value_9b2f9400,omitempty"`
	HsAnalyticsSourceTimestampEarliestValue25a3a52c                       string  `json:"hs_analytics_source_timestamp_earliest_value_25a3a52c,omitempty"`
	HsAvatarFilemanagerKey                                                string  `json:"hs_avatar_filemanager_key,omitempty"`
	HsCreatedByUserId                                                     int64   `json:"hs_created_by_user_id,omitempty"`
	HsCreatedate                                                          string  `json:"hs_createdate,omitempty"`
	HsDateEnteredCustomer                                                 string  `json:"hs_date_entered_customer,omitempty"`
	HsDateEnteredEvangelist                                               string  `json:"hs_date_entered_evangelist,omitempty"`
	HsDateEnteredLead                                                     string  `json:"hs_date_entered_lead,omitempty"`
	HsDateEnteredMarketingqualifiedlead                                   string  `json:"hs_date_entered_marketingqualifiedlead,omitempty"`
	HsDateEnteredOpportunity                                              string  `json:"hs_date_entered_opportunity,omitempty"`
	HsDateEnteredOther                                                    string  `json:"hs_date_entered_other,omitempty"`
	HsDateEnteredSalesqualifiedlead                                       string  `json:"hs_date_entered_salesqualifiedlead,omitempty"`
	HsDateEnteredSubscriber                                               string  `json:"hs_date_entered_subscriber,omitempty"`
	HsDateExitedCustomer                                                  string  `json:"hs_date_exited_customer,omitempty"`
	HsDateExitedEvangelist                                                string  `json:"hs_date_exited_evangelist,omitempty"`
	HsDateExitedLead                                                      string  `json:"hs_date_exited_lead,omitempty"`
	HsDateExitedMarketingqualifiedlead                                    string  `json:"hs_date_exited_marketingqualifiedlead,omitempty"`
	HsDateExitedOpportunity                                               string  `json:"hs_date_exited_opportunity,omitempty"`
	HsDateExitedOther                                                     string  `json:"hs_date_exited_other,omitempty"`
	HsDateExitedSalesqualifiedlead                                        string  `json:"hs_date_exited_salesqualifiedlead,omitempty"`
	HsDateExitedSubscriber                                                string  `json:"hs_date_exited_subscriber,omitempty"`
	HsIdealCustomerProfile                                                string  `json:"hs_ideal_customer_profile,omitempty"`
	HsIsTargetAccount                                                     bool    `json:"hs_is_target_account,omitempty"`
	HsLastBookedMeetingDate                                               string  `json:"hs_last_booked_meeting_date,omitempty"`
	HsLastLoggedCallDate                                                  string  `json:"hs_last_logged_call_date,omitempty"`
	HsLastOpenTaskDate                                                    string  `json:"hs_last_open_task_date,omitempty"`
	HsLastSalesActivityDate                                               string  `json:"hs_last_sales_activity_date,omitempty"`
	HsLastSalesActivityTimestamp                                          string  `json:"hs_last_sales_activity_timestamp,omitempty"`
	HsLastmodifieddate                                                    string  `json:"hs_lastmodifieddate,omitempty"`
	HsLatestCreatedateOfActiveSubscriptions                               string  `json:"hs_latest_createdate_of_active_subscriptions,omitempty"`
	HsMergedObjectIds                                                     string  `json:"hs_merged_object_ids,omitempty"`
	HsNumBlockers                                                         int64   `json:"hs_num_blockers,omitempty"`
	HsNumContactsWithBuyingRoles                                          int64   `json:"hs_num_contacts_with_buying_roles,omitempty"`
	HsNumDecisionMakers                                                   int64   `json:"hs_num_decision_makers,omitempty"`
	HsNumOpenDeals                                                        int64   `json:"hs_num_open_deals,omitempty"`
	HsObjectId                                                            string  `json:"hs_object_id,omitempty"`
	HsPipeline                                                            string  `json:"hs_pipeline,omitempty"`
	HsPredictivecontactscoreV2                                            int64   `json:"hs_predictivecontactscore_v2,omitempty"`
	HsPredictivecontactscoreV2NextMaxMaxD4e58c1e                          int64   `json:"hs_predictivecontactscore_v2_next_max_max_d4e58c1e,omitempty"`
	HsTargetAccount                                                       string  `json:"hs_target_account,omitempty"`
	HsTargetAccountProbability                                            int64   `json:"hs_target_account_probability,omitempty"`
	HsTargetAccountRecommendationSnoozeTime                               string  `json:"hs_target_account_recommendation_snooze_time,omitempty"`
	HsTargetAccountRecommendationState                                    string  `json:"hs_target_account_recommendation_state,omitempty"`
	HsTimeInCustomer                                                      int64   `json:"hs_time_in_customer,omitempty"`
	HsTimeInEvangelist                                                    int64   `json:"hs_time_in_evangelist,omitempty"`
	HsTimeInLead                                                          int64   `json:"hs_time_in_lead,omitempty"`
	HsTimeInMarketingqualifiedlead                                        int64   `json:"hs_time_in_marketingqualifiedlead,omitempty"`
	HsTimeInOpportunity                                                   int64   `json:"hs_time_in_opportunity,omitempty"`
	HsTimeInOther                                                         int64   `json:"hs_time_in_other,omitempty"`
	HsTimeInSalesqualifiedlead                                            int64   `json:"hs_time_in_salesqualifiedlead,omitempty"`
	HsTimeInSubscriber                                                    int64   `json:"hs_time_in_subscriber,omitempty"`
	HsTotalDealValue                                                      int64   `json:"hs_total_deal_value,omitempty"`
	HsUniqueCreationKey                                                   string  `json:"hs_unique_creation_key,omitempty"`
	HsUpdatedByUserId                                                     int64   `json:"hs_updated_by_user_id,omitempty"`
	HsUserIdsOfAllNotificationFollowers                                   string  `json:"hs_user_ids_of_all_notification_followers,omitempty"`
	HsUserIdsOfAllNotificationUnfollowers                                 string  `json:"hs_user_ids_of_all_notification_unfollowers,omitempty"`
	HsUserIdsOfAllOwners                                                  string  `json:"hs_user_ids_of_all_owners,omitempty"`
	HubspotOwnerAssigneddate                                              string  `json:"hubspot_owner_assigneddate,omitempty"`
	IsPublic                                                              bool    `json:"is_public,omitempty"`
	NumAssociatedContacts                                                 int64   `json:"num_associated_contacts,omitempty"`
	NumAssociatedDeals                                                    int64   `json:"num_associated_deals,omitempty"`
	NumConversionEvents                                                   int64   `json:"num_conversion_events,omitempty"`
	NumConversionEventsCardinalitySumD095f14b                             int64   `json:"num_conversion_events_cardinality_sum_d095f14b,omitempty"`
	RecentConversionDate                                                  string  `json:"recent_conversion_date,omitempty"`
	RecentConversionDateTimestampLatestValue72856da1                      string  `json:"recent_conversion_date_timestamp_latest_value_72856da1,omitempty"`
	RecentConversionEventName                                             string  `json:"recent_conversion_event_name,omitempty"`
	RecentConversionEventNameTimestampLatestValue66c820bf                 string  `json:"recent_conversion_event_name_timestamp_latest_value_66c820bf,omitempty"`
	RecentDealAmount                                                      float64 `json:"recent_deal_amount,omitempty"`
	RecentDealCloseDate                                                   string  `json:"recent_deal_close_date,omitempty"`
	Timezone                                                              string  `json:"timezone,omitempty"`
	TotalMoneyRaised                                                      string  `json:"total_money_raised,omitempty"`
	TotalRevenue                                                          int64   `json:"total_revenue,omitempty"`
	Name                                                                  string  `json:"name,omitempty"`
	Notes                                                                 string  `json:"notes,omitempty"`
	Owneremail                                                            string  `json:"owneremail,omitempty"`
	Status                                                                string  `json:"status,omitempty"`
	Twitterhandle                                                         string  `json:"twitterhandle,omitempty"`
	Ownername                                                             string  `json:"ownername,omitempty"`
	Phone                                                                 string  `json:"phone,omitempty"`
	Twitterbio                                                            string  `json:"twitterbio,omitempty"`
	Twitterfollowers                                                      int64   `json:"twitterfollowers,omitempty"`
	Address                                                               string  `json:"address,omitempty"`
	Address2                                                              string  `json:"address2,omitempty"`
	FacebookCompanyPage                                                   string  `json:"facebook_company_page,omitempty"`
	City                                                                  string  `json:"city,omitempty"`
	LinkedinCompanyPage                                                   string  `json:"linkedin_company_page,omitempty"`
	Linkedinbio                                                           string  `json:"linkedinbio,omitempty"`
	State                                                                 string  `json:"state,omitempty"`
	GoogleplusPage                                                        string  `json:"googleplus_page,omitempty"`
	EngagementsLastMeetingBooked                                          string  `json:"engagements_last_meeting_booked,omitempty"`
	EngagementsLastMeetingBookedCampaign                                  string  `json:"engagements_last_meeting_booked_campaign,omitempty"`
	EngagementsLastMeetingBookedMedium                                    string  `json:"engagements_last_meeting_booked_medium,omitempty"`
	EngagementsLastMeetingBookedSource                                    string  `json:"engagements_last_meeting_booked_source,omitempty"`
	HsLatestMeetingActivity                                               string  `json:"hs_latest_meeting_activity,omitempty"`
	HsSalesEmailLastReplied                                               string  `json:"hs_sales_email_last_replied,omitempty"`
	HubspotOwnerId                                                        string  `json:"hubspot_owner_id,omitempty"`
	NotesLastContacted                                                    string  `json:"notes_last_contacted,omitempty"`
	NotesLastUpdated                                                      string  `json:"notes_last_updated,omitempty"`
	NotesNextActivityDate                                                 string  `json:"notes_next_activity_date,omitempty"`
	NumContactedNotes                                                     int64   `json:"num_contacted_notes,omitempty"`
	NumNotes                                                              int64   `json:"num_notes,omitempty"`
	Zip                                                                   string  `json:"zip,omitempty"`
	Country                                                               string  `json:"country,omitempty"`
	HubspotTeamId                                                         string  `json:"hubspot_team_id,omitempty"`
	HsAllOwnerIds                                                         string  `json:"hs_all_owner_ids,omitempty"`
	Website                                                               string  `json:"website,omitempty"`
	Domain                                                                string  `json:"domain,omitempty"`
	HsAllTeamIds                                                          string  `json:"hs_all_team_ids,omitempty"`
	HsAllAccessibleTeamIds                                                string  `json:"hs_all_accessible_team_ids,omitempty"`
	Numberofemployees                                                     int64   `json:"numberofemployees,omitempty"`
	Industry                                                              string  `json:"industry,omitempty"`
	Annualrevenue                                                         int64   `json:"annualrevenue,omitempty"`
	Lifecyclestage                                                        string  `json:"lifecyclestage,omitempty"`
	HsLeadStatus                                                          string  `json:"hs_lead_status,omitempty"`
	HsParentCompanyId                                                     int64   `json:"hs_parent_company_id,omitempty"`
	Type                                                                  string  `json:"type,omitempty"`
	Description                                                           string  `json:"description,omitempty"`
	HsNumChildCompanies                                                   int64   `json:"hs_num_child_companies,omitempty"`
	Hubspotscore                                                          int64   `json:"hubspotscore,omitempty"`
	Createdate                                                            string  `json:"createdate,omitempty"`
	Closedate                                                             string  `json:"closedate,omitempty"`
	FirstContactCreatedate                                                string  `json:"first_contact_createdate,omitempty"`
	DaysToClose                                                           int64   `json:"days_to_close,omitempty"`
	WebTechnologies                                                       string  `json:"web_technologies,omitempty"`
}