package crm

type CompanyProperties struct {
	AboutUs                                                               string  `json:"about_us"`
	ClosedateTimestampEarliestValueA2a17e6e                               string  `json:"closedate_timestamp_earliest_value_a2a17e6e"`
	Cohort                                                                string  `json:"cohort"`
	DealByCompany                                                         string  `json:"deal_by_company"`
	Facebookfans                                                          int64   `json:"facebookfans"`
	FirstContactCreatedateTimestampEarliestValue78b50eea                  string  `json:"first_contact_createdate_timestamp_earliest_value_78b50eea"`
	FirstConversionDate                                                   string  `json:"first_conversion_date"`
	FirstConversionDateTimestampEarliestValue61f58f2c                     string  `json:"first_conversion_date_timestamp_earliest_value_61f58f2c"`
	FirstConversionEventName                                              string  `json:"first_conversion_event_name"`
	FirstConversionEventNameTimestampEarliestValue68ddae0a                string  `json:"first_conversion_event_name_timestamp_earliest_value_68ddae0a"`
	FirstDealCreatedDate                                                  string  `json:"first_deal_created_date"`
	FoundedYear                                                           string  `json:"founded_year"`
	HsAdditionalDomains                                                   string  `json:"hs_additional_domains"`
	HsAllAssignedBusinessUnitIds                                          string  `json:"hs_all_assigned_business_unit_ids"`
	HsAnalyticsFirstTimestamp                                             string  `json:"hs_analytics_first_timestamp"`
	HsAnalyticsFirstTimestampTimestampEarliestValue11e3a63a               string  `json:"hs_analytics_first_timestamp_timestamp_earliest_value_11e3a63a"`
	HsAnalyticsFirstTouchConvertingCampaign                               string  `json:"hs_analytics_first_touch_converting_campaign"`
	HsAnalyticsFirstTouchConvertingCampaignTimestampEarliestValue4757fe10 string  `json:"hs_analytics_first_touch_converting_campaign_timestamp_earliest_value_4757fe10"`
	HsAnalyticsFirstVisitTimestamp                                        string  `json:"hs_analytics_first_visit_timestamp"`
	HsAnalyticsFirstVisitTimestampTimestampEarliestValueAccc17ae          string  `json:"hs_analytics_first_visit_timestamp_timestamp_earliest_value_accc17ae"`
	HsAnalyticsLastTimestamp                                              string  `json:"hs_analytics_last_timestamp"`
	HsAnalyticsLastTimestampTimestampLatestValue4e16365a                  string  `json:"hs_analytics_last_timestamp_timestamp_latest_value_4e16365a"`
	HsAnalyticsLastTouchConvertingCampaign                                string  `json:"hs_analytics_last_touch_converting_campaign"`
	HsAnalyticsLastTouchConvertingCampaignTimestampLatestValue81a64e30    string  `json:"hs_analytics_last_touch_converting_campaign_timestamp_latest_value_81a64e30"`
	HsAnalyticsLastVisitTimestamp                                         string  `json:"hs_analytics_last_visit_timestamp"`
	HsAnalyticsLastVisitTimestampTimestampLatestValue999a0fce             string  `json:"hs_analytics_last_visit_timestamp_timestamp_latest_value_999a0fce"`
	HsAnalyticsLatestSource                                               string  `json:"hs_analytics_latest_source"`
	HsAnalyticsLatestSourceData1                                          string  `json:"hs_analytics_latest_source_data_1"`
	HsAnalyticsLatestSourceData2                                          string  `json:"hs_analytics_latest_source_data_2"`
	HsAnalyticsLatestSourceTimestamp                                      string  `json:"hs_analytics_latest_source_timestamp"`
	HsAnalyticsNumPageViews                                               int64   `json:"hs_analytics_num_page_views"`
	HsAnalyticsNumPageViewsCardinalitySumE46e85b0                         int64   `json:"hs_analytics_num_page_views_cardinality_sum_e46e85b0"`
	HsAnalyticsNumVisits                                                  int64   `json:"hs_analytics_num_visits"`
	HsAnalyticsNumVisitsCardinalitySum53d952a6                            int64   `json:"hs_analytics_num_visits_cardinality_sum_53d952a6"`
	HsAnalyticsSource                                                     string  `json:"hs_analytics_source"`
	HsAnalyticsSourceData1                                                string  `json:"hs_analytics_source_data_1"`
	HsAnalyticsSourceData1TimestampEarliestValue9b2f1fa1                  string  `json:"hs_analytics_source_data_1_timestamp_earliest_value_9b2f1fa1"`
	HsAnalyticsSourceData2                                                string  `json:"hs_analytics_source_data_2"`
	HsAnalyticsSourceData2TimestampEarliestValue9b2f9400                  string  `json:"hs_analytics_source_data_2_timestamp_earliest_value_9b2f9400"`
	HsAnalyticsSourceTimestampEarliestValue25a3a52c                       string  `json:"hs_analytics_source_timestamp_earliest_value_25a3a52c"`
	HsAvatarFilemanagerKey                                                string  `json:"hs_avatar_filemanager_key"`
	HsCreatedByUserId                                                     int64   `json:"hs_created_by_user_id"`
	HsCreatedate                                                          string  `json:"hs_createdate"`
	HsDateEnteredCustomer                                                 string  `json:"hs_date_entered_customer"`
	HsDateEnteredEvangelist                                               string  `json:"hs_date_entered_evangelist"`
	HsDateEnteredLead                                                     string  `json:"hs_date_entered_lead"`
	HsDateEnteredMarketingqualifiedlead                                   string  `json:"hs_date_entered_marketingqualifiedlead"`
	HsDateEnteredOpportunity                                              string  `json:"hs_date_entered_opportunity"`
	HsDateEnteredOther                                                    string  `json:"hs_date_entered_other"`
	HsDateEnteredSalesqualifiedlead                                       string  `json:"hs_date_entered_salesqualifiedlead"`
	HsDateEnteredSubscriber                                               string  `json:"hs_date_entered_subscriber"`
	HsDateExitedCustomer                                                  string  `json:"hs_date_exited_customer"`
	HsDateExitedEvangelist                                                string  `json:"hs_date_exited_evangelist"`
	HsDateExitedLead                                                      string  `json:"hs_date_exited_lead"`
	HsDateExitedMarketingqualifiedlead                                    string  `json:"hs_date_exited_marketingqualifiedlead"`
	HsDateExitedOpportunity                                               string  `json:"hs_date_exited_opportunity"`
	HsDateExitedOther                                                     string  `json:"hs_date_exited_other"`
	HsDateExitedSalesqualifiedlead                                        string  `json:"hs_date_exited_salesqualifiedlead"`
	HsDateExitedSubscriber                                                string  `json:"hs_date_exited_subscriber"`
	HsIdealCustomerProfile                                                string  `json:"hs_ideal_customer_profile"`
	HsIsTargetAccount                                                     bool    `json:"hs_is_target_account"`
	HsLastBookedMeetingDate                                               string  `json:"hs_last_booked_meeting_date"`
	HsLastLoggedCallDate                                                  string  `json:"hs_last_logged_call_date"`
	HsLastOpenTaskDate                                                    string  `json:"hs_last_open_task_date"`
	HsLastSalesActivityDate                                               string  `json:"hs_last_sales_activity_date"`
	HsLastSalesActivityTimestamp                                          string  `json:"hs_last_sales_activity_timestamp"`
	HsLastmodifieddate                                                    string  `json:"hs_lastmodifieddate"`
	HsLatestCreatedateOfActiveSubscriptions                               string  `json:"hs_latest_createdate_of_active_subscriptions"`
	HsMergedObjectIds                                                     string  `json:"hs_merged_object_ids"`
	HsNumBlockers                                                         int64   `json:"hs_num_blockers"`
	HsNumContactsWithBuyingRoles                                          int64   `json:"hs_num_contacts_with_buying_roles"`
	HsNumDecisionMakers                                                   int64   `json:"hs_num_decision_makers"`
	HsNumOpenDeals                                                        int64   `json:"hs_num_open_deals"`
	HsObjectId                                                            string  `json:"hs_object_id"`
	HsPipeline                                                            string  `json:"hs_pipeline"`
	HsPredictivecontactscoreV2                                            int64   `json:"hs_predictivecontactscore_v2"`
	HsPredictivecontactscoreV2NextMaxMaxD4e58c1e                          int64   `json:"hs_predictivecontactscore_v2_next_max_max_d4e58c1e"`
	HsTargetAccount                                                       string  `json:"hs_target_account"`
	HsTargetAccountProbability                                            int64   `json:"hs_target_account_probability"`
	HsTargetAccountRecommendationSnoozeTime                               string  `json:"hs_target_account_recommendation_snooze_time"`
	HsTargetAccountRecommendationState                                    string  `json:"hs_target_account_recommendation_state"`
	HsTimeInCustomer                                                      int64   `json:"hs_time_in_customer"`
	HsTimeInEvangelist                                                    int64   `json:"hs_time_in_evangelist"`
	HsTimeInLead                                                          int64   `json:"hs_time_in_lead"`
	HsTimeInMarketingqualifiedlead                                        int64   `json:"hs_time_in_marketingqualifiedlead"`
	HsTimeInOpportunity                                                   int64   `json:"hs_time_in_opportunity"`
	HsTimeInOther                                                         int64   `json:"hs_time_in_other"`
	HsTimeInSalesqualifiedlead                                            int64   `json:"hs_time_in_salesqualifiedlead"`
	HsTimeInSubscriber                                                    int64   `json:"hs_time_in_subscriber"`
	HsTotalDealValue                                                      int64   `json:"hs_total_deal_value"`
	HsUniqueCreationKey                                                   string  `json:"hs_unique_creation_key"`
	HsUpdatedByUserId                                                     int64   `json:"hs_updated_by_user_id"`
	HsUserIdsOfAllNotificationFollowers                                   string  `json:"hs_user_ids_of_all_notification_followers"`
	HsUserIdsOfAllNotificationUnfollowers                                 string  `json:"hs_user_ids_of_all_notification_unfollowers"`
	HsUserIdsOfAllOwners                                                  string  `json:"hs_user_ids_of_all_owners"`
	HubspotOwnerAssigneddate                                              string  `json:"hubspot_owner_assigneddate"`
	IsPublic                                                              bool    `json:"is_public"`
	NumAssociatedContacts                                                 int64   `json:"num_associated_contacts"`
	NumAssociatedDeals                                                    int64   `json:"num_associated_deals"`
	NumConversionEvents                                                   int64   `json:"num_conversion_events"`
	NumConversionEventsCardinalitySumD095f14b                             int64   `json:"num_conversion_events_cardinality_sum_d095f14b"`
	RecentConversionDate                                                  string  `json:"recent_conversion_date"`
	RecentConversionDateTimestampLatestValue72856da1                      string  `json:"recent_conversion_date_timestamp_latest_value_72856da1"`
	RecentConversionEventName                                             string  `json:"recent_conversion_event_name"`
	RecentConversionEventNameTimestampLatestValue66c820bf                 string  `json:"recent_conversion_event_name_timestamp_latest_value_66c820bf"`
	RecentDealAmount                                                      float64 `json:"recent_deal_amount"`
	RecentDealCloseDate                                                   string  `json:"recent_deal_close_date"`
	Timezone                                                              string  `json:"timezone"`
	TotalMoneyRaised                                                      string  `json:"total_money_raised"`
	TotalRevenue                                                          int64   `json:"total_revenue"`
	Name                                                                  string  `json:"name"`
	Notes                                                                 string  `json:"notes"`
	Owneremail                                                            string  `json:"owneremail"`
	Status                                                                string  `json:"status"`
	Twitterhandle                                                         string  `json:"twitterhandle"`
	Ownername                                                             string  `json:"ownername"`
	Phone                                                                 string  `json:"phone"`
	Twitterbio                                                            string  `json:"twitterbio"`
	Twitterfollowers                                                      int64   `json:"twitterfollowers"`
	Address                                                               string  `json:"address"`
	Address2                                                              string  `json:"address2"`
	FacebookCompanyPage                                                   string  `json:"facebook_company_page"`
	City                                                                  string  `json:"city"`
	LinkedinCompanyPage                                                   string  `json:"linkedin_company_page"`
	Linkedinbio                                                           string  `json:"linkedinbio"`
	State                                                                 string  `json:"state"`
	GoogleplusPage                                                        string  `json:"googleplus_page"`
	EngagementsLastMeetingBooked                                          string  `json:"engagements_last_meeting_booked"`
	EngagementsLastMeetingBookedCampaign                                  string  `json:"engagements_last_meeting_booked_campaign"`
	EngagementsLastMeetingBookedMedium                                    string  `json:"engagements_last_meeting_booked_medium"`
	EngagementsLastMeetingBookedSource                                    string  `json:"engagements_last_meeting_booked_source"`
	HsLatestMeetingActivity                                               string  `json:"hs_latest_meeting_activity"`
	HsSalesEmailLastReplied                                               string  `json:"hs_sales_email_last_replied"`
	HubspotOwnerId                                                        string  `json:"hubspot_owner_id"`
	NotesLastContacted                                                    string  `json:"notes_last_contacted"`
	NotesLastUpdated                                                      string  `json:"notes_last_updated"`
	NotesNextActivityDate                                                 string  `json:"notes_next_activity_date"`
	NumContactedNotes                                                     int64   `json:"num_contacted_notes"`
	NumNotes                                                              int64   `json:"num_notes"`
	Zip                                                                   string  `json:"zip"`
	Country                                                               string  `json:"country"`
	HubspotTeamId                                                         string  `json:"hubspot_team_id"`
	HsAllOwnerIds                                                         string  `json:"hs_all_owner_ids"`
	Website                                                               string  `json:"website"`
	Domain                                                                string  `json:"domain"`
	HsAllTeamIds                                                          string  `json:"hs_all_team_ids"`
	HsAllAccessibleTeamIds                                                string  `json:"hs_all_accessible_team_ids"`
	Numberofemployees                                                     int64   `json:"numberofemployees"`
	Industry                                                              string  `json:"industry"`
	Annualrevenue                                                         int64   `json:"annualrevenue"`
	Lifecyclestage                                                        string  `json:"lifecyclestage"`
	HsLeadStatus                                                          string  `json:"hs_lead_status"`
	HsParentCompanyId                                                     int64   `json:"hs_parent_company_id"`
	Type                                                                  string  `json:"type"`
	Description                                                           string  `json:"description"`
	HsNumChildCompanies                                                   int64   `json:"hs_num_child_companies"`
	Hubspotscore                                                          int64   `json:"hubspotscore"`
	Createdate                                                            string  `json:"createdate"`
	Closedate                                                             string  `json:"closedate"`
	FirstContactCreatedate                                                string  `json:"first_contact_createdate"`
	DaysToClose                                                           int64   `json:"days_to_close"`
	WebTechnologies                                                       string  `json:"web_technologies"`
}