package crm

type ContactProperties struct {
	CompanySize                                      string  `json:"company_size,omitempty"`
	DateOfBirth                                      string  `json:"date_of_birth,omitempty"`
	DaysToClose                                      int64   `json:"days_to_close,omitempty"`
	Degree                                           string  `json:"degree,omitempty"`
	FieldOfStudy                                     string  `json:"field_of_study,omitempty"`
	FirstConversionDate                              string  `json:"first_conversion_date,omitempty"`
	FirstConversionEventName                         string  `json:"first_conversion_event_name,omitempty"`
	FirstDealCreatedDate                             string  `json:"first_deal_created_date,omitempty"`
	Gender                                           string  `json:"gender,omitempty"`
	GraduationDate                                   string  `json:"graduation_date,omitempty"`
	HsAdditionalEmails                               string  `json:"hs_additional_emails,omitempty"`
	HsAllAssignedBusinessUnitIds                     string  `json:"hs_all_assigned_business_unit_ids,omitempty"`
	HsAllContactVids                                 string  `json:"hs_all_contact_vids,omitempty"`
	HsAnalyticsFirstTouchConvertingCampaign          string  `json:"hs_analytics_first_touch_converting_campaign,omitempty"`
	HsAnalyticsLastTouchConvertingCampaign           string  `json:"hs_analytics_last_touch_converting_campaign,omitempty"`
	HsAvatarFilemanagerKey                           string  `json:"hs_avatar_filemanager_key,omitempty"`
	HsBuyingRole                                     string  `json:"hs_buying_role,omitempty"`
	HsCalculatedFormSubmissions                      string  `json:"hs_calculated_form_submissions,omitempty"`
	HsCalculatedMergedVids                           string  `json:"hs_calculated_merged_vids,omitempty"`
	HsCalculatedMobileNumber                         string  `json:"hs_calculated_mobile_number,omitempty"`
	HsCalculatedPhoneNumber                          string  `json:"hs_calculated_phone_number,omitempty"`
	HsCalculatedPhoneNumberAreaCode                  string  `json:"hs_calculated_phone_number_area_code,omitempty"`
	HsCalculatedPhoneNumberCountryCode               string  `json:"hs_calculated_phone_number_country_code,omitempty"`
	HsCalculatedPhoneNumberRegionCode                string  `json:"hs_calculated_phone_number_region_code,omitempty"`
	HsContentMembershipEmailConfirmed                bool    `json:"hs_content_membership_email_confirmed,omitempty"`
	HsContentMembershipNotes                         string  `json:"hs_content_membership_notes,omitempty"`
	HsContentMembershipRegisteredAt                  string  `json:"hs_content_membership_registered_at,omitempty"`
	HsContentMembershipRegistrationDomainSentTo      string  `json:"hs_content_membership_registration_domain_sent_to,omitempty"`
	HsContentMembershipRegistrationEmailSentAt       string  `json:"hs_content_membership_registration_email_sent_at,omitempty"`
	HsContentMembershipStatus                        string  `json:"hs_content_membership_status,omitempty"`
	HsConversationsVisitorEmail                      string  `json:"hs_conversations_visitor_email,omitempty"`
	HsCountIsUnworked                                int64   `json:"hs_count_is_unworked,omitempty"`
	HsCountIsWorked                                  int64   `json:"hs_count_is_worked,omitempty"`
	HsCreatedByConversations                         bool    `json:"hs_created_by_conversations,omitempty"`
	HsCreatedByUserId                                string  `json:"hs_created_by_user_id,omitempty"`
	HsCreatedate                                     string  `json:"hs_createdate,omitempty"`
	HsDateEnteredCustomer                            string  `json:"hs_date_entered_customer,omitempty"`
	HsDateEnteredEvangelist                          string  `json:"hs_date_entered_evangelist,omitempty"`
	HsDateEnteredLead                                string  `json:"hs_date_entered_lead,omitempty"`
	HsDateEnteredMarketingqualifiedlead              string  `json:"hs_date_entered_marketingqualifiedlead,omitempty"`
	HsDateEnteredOpportunity                         string  `json:"hs_date_entered_opportunity,omitempty"`
	HsDateEnteredOther                               string  `json:"hs_date_entered_other,omitempty"`
	HsDateEnteredSalesqualifiedlead                  string  `json:"hs_date_entered_salesqualifiedlead,omitempty"`
	HsDateEnteredSubscriber                          string  `json:"hs_date_entered_subscriber,omitempty"`
	HsDateExitedCustomer                             string  `json:"hs_date_exited_customer,omitempty"`
	HsDateExitedEvangelist                           string  `json:"hs_date_exited_evangelist,omitempty"`
	HsDateExitedLead                                 string  `json:"hs_date_exited_lead,omitempty"`
	HsDateExitedMarketingqualifiedlead               string  `json:"hs_date_exited_marketingqualifiedlead,omitempty"`
	HsDateExitedOpportunity                          string  `json:"hs_date_exited_opportunity,omitempty"`
	HsDateExitedOther                                string  `json:"hs_date_exited_other,omitempty"`
	HsDateExitedSalesqualifiedlead                   string  `json:"hs_date_exited_salesqualifiedlead,omitempty"`
	HsDateExitedSubscriber                           string  `json:"hs_date_exited_subscriber,omitempty"`
	HsDocumentLastRevisited                          string  `json:"hs_document_last_revisited,omitempty"`
	HsEmailBadAddress                                bool    `json:"hs_email_bad_address,omitempty"`
	HsEmailCustomerQuarantinedReason                 string  `json:"hs_email_customer_quarantined_reason,omitempty"`
	HsEmailDomain                                    string  `json:"hs_email_domain,omitempty"`
	HsEmailHardBounceReason                          string  `json:"hs_email_hard_bounce_reason,omitempty"`
	HsEmailHardBounceReasonEnum                      string  `json:"hs_email_hard_bounce_reason_enum,omitempty"`
	HsEmailQuarantined                               bool    `json:"hs_email_quarantined,omitempty"`
	HsEmailQuarantinedReason                         string  `json:"hs_email_quarantined_reason,omitempty"`
	HsEmailRecipientFatigueRecoveryTime              string  `json:"hs_email_recipient_fatigue_recovery_time,omitempty"`
	HsEmailSendsSinceLastEngagement                  int64   `json:"hs_email_sends_since_last_engagement,omitempty"`
	HsEmailconfirmationstatus                        string  `json:"hs_emailconfirmationstatus,omitempty"`
	HsFacebookAdClicked                              bool    `json:"hs_facebook_ad_clicked,omitempty"`
	HsFacebookClickId                                string  `json:"hs_facebook_click_id,omitempty"`
	HsFacebookid                                     string  `json:"hs_facebookid,omitempty"`
	HsFeedbackLastNpsFollowUp                        string  `json:"hs_feedback_last_nps_follow_up,omitempty"`
	HsFeedbackLastNpsRating                          string  `json:"hs_feedback_last_nps_rating,omitempty"`
	HsFeedbackLastSurveyDate                         string  `json:"hs_feedback_last_survey_date,omitempty"`
	HsFeedbackShowNpsWebSurvey                       bool    `json:"hs_feedback_show_nps_web_survey,omitempty"`
	HsFirstEngagementObjectId                        string  `json:"hs_first_engagement_object_id,omitempty"`
	HsFirstSubscriptionCreateDate                    string  `json:"hs_first_subscription_create_date,omitempty"`
	HsGoogleClickId                                  string  `json:"hs_google_click_id,omitempty"`
	HsGoogleplusid                                   string  `json:"hs_googleplusid,omitempty"`
	HsHasActiveSubscription                          int64   `json:"hs_has_active_subscription,omitempty"`
	HsIpTimezone                                     string  `json:"hs_ip_timezone,omitempty"`
	HsIsContact                                      string  `json:"hs_is_contact,omitempty"`
	HsIsUnworked                                     string  `json:"hs_is_unworked,omitempty"`
	HsLastSalesActivityDate                          string  `json:"hs_last_sales_activity_date,omitempty"`
	HsLastSalesActivityTimestamp                     string  `json:"hs_last_sales_activity_timestamp,omitempty"`
	HsLastmodifieddate                               string  `json:"hs_lastmodifieddate,omitempty"`
	HsLatestSequenceEndedDate                        string  `json:"hs_latest_sequence_ended_date,omitempty"`
	HsLatestSequenceEnrolled                         int64   `json:"hs_latest_sequence_enrolled,omitempty"`
	HsLatestSequenceEnrolledDate                     string  `json:"hs_latest_sequence_enrolled_date,omitempty"`
	HsLatestSequenceFinishedDate                     string  `json:"hs_latest_sequence_finished_date,omitempty"`
	HsLatestSequenceUnenrolledDate                   string  `json:"hs_latest_sequence_unenrolled_date,omitempty"`
	HsLatestSourceTimestamp                          string  `json:"hs_latest_source_timestamp,omitempty"`
	HsLatestSubscriptionCreateDate                   string  `json:"hs_latest_subscription_create_date,omitempty"`
	HsLeadStatus                                     string  `json:"hs_lead_status,omitempty"`
	HsLegalBasis                                     string  `json:"hs_legal_basis,omitempty"`
	HsLinkedinid                                     string  `json:"hs_linkedinid,omitempty"`
	HsMarketableReasonId                             string  `json:"hs_marketable_reason_id,omitempty"`
	HsMarketableReasonType                           string  `json:"hs_marketable_reason_type,omitempty"`
	HsMarketableStatus                               string  `json:"hs_marketable_status,omitempty"`
	HsMarketableUntilRenewal                         string  `json:"hs_marketable_until_renewal,omitempty"`
	HsMergedObjectIds                                string  `json:"hs_merged_object_ids,omitempty"`
	HsObjectId                                       string  `json:"hs_object_id,omitempty"`
	HsPipeline                                       string  `json:"hs_pipeline,omitempty"`
	HsPredictivecontactscoreV2                       int64   `json:"hs_predictivecontactscore_v2,omitempty"`
	HsPredictivescoringtier                          string  `json:"hs_predictivescoringtier,omitempty"`
	HsSaFirstEngagementDate                          string  `json:"hs_sa_first_engagement_date,omitempty"`
	HsSaFirstEngagementDescr                         string  `json:"hs_sa_first_engagement_descr,omitempty"`
	HsSaFirstEngagementObjectType                    string  `json:"hs_sa_first_engagement_object_type,omitempty"`
	HsSalesEmailLastClicked                          string  `json:"hs_sales_email_last_clicked,omitempty"`
	HsSalesEmailLastOpened                           string  `json:"hs_sales_email_last_opened,omitempty"`
	HsSearchableCalculatedInternationalMobileNumber  string  `json:"hs_searchable_calculated_international_mobile_number,omitempty"`
	HsSearchableCalculatedInternationalPhoneNumber   string  `json:"hs_searchable_calculated_international_phone_number,omitempty"`
	HsSearchableCalculatedMobileNumber               string  `json:"hs_searchable_calculated_mobile_number,omitempty"`
	HsSearchableCalculatedPhoneNumber                string  `json:"hs_searchable_calculated_phone_number,omitempty"`
	HsSequencesActivelyEnrolledCount                 int64   `json:"hs_sequences_actively_enrolled_count,omitempty"`
	HsSequencesEnrolledCount                         int64   `json:"hs_sequences_enrolled_count,omitempty"`
	HsSequencesIsEnrolled                            bool    `json:"hs_sequences_is_enrolled,omitempty"`
	HsTestpurge                                      string  `json:"hs_testpurge,omitempty"`
	HsTestrollback                                   string  `json:"hs_testrollback,omitempty"`
	HsTimeBetweenContactCreationAndDealClose         int64   `json:"hs_time_between_contact_creation_and_deal_close,omitempty"`
	HsTimeBetweenContactCreationAndDealCreation      int64   `json:"hs_time_between_contact_creation_and_deal_creation,omitempty"`
	HsTimeInCustomer                                 int64   `json:"hs_time_in_customer,omitempty"`
	HsTimeInEvangelist                               int64   `json:"hs_time_in_evangelist,omitempty"`
	HsTimeInLead                                     int64   `json:"hs_time_in_lead,omitempty"`
	HsTimeInMarketingqualifiedlead                   int64   `json:"hs_time_in_marketingqualifiedlead,omitempty"`
	HsTimeInOpportunity                              int64   `json:"hs_time_in_opportunity,omitempty"`
	HsTimeInOther                                    int64   `json:"hs_time_in_other,omitempty"`
	HsTimeInSalesqualifiedlead                       int64   `json:"hs_time_in_salesqualifiedlead,omitempty"`
	HsTimeInSubscriber                               int64   `json:"hs_time_in_subscriber,omitempty"`
	HsTimeToFirstEngagement                          int64   `json:"hs_time_to_first_engagement,omitempty"`
	HsTimeToMoveFromLeadToCustomer                   int64   `json:"hs_time_to_move_from_lead_to_customer,omitempty"`
	HsTimeToMoveFromMarketingqualifiedleadToCustomer int64   `json:"hs_time_to_move_from_marketingqualifiedlead_to_customer,omitempty"`
	HsTimeToMoveFromOpportunityToCustomer            int64   `json:"hs_time_to_move_from_opportunity_to_customer,omitempty"`
	HsTimeToMoveFromSalesqualifiedleadToCustomer     int64   `json:"hs_time_to_move_from_salesqualifiedlead_to_customer,omitempty"`
	HsTimeToMoveFromSubscriberToCustomer             int64   `json:"hs_time_to_move_from_subscriber_to_customer,omitempty"`
	HsTimezone                                       string  `json:"hs_timezone,omitempty"`
	HsTwitterid                                      string  `json:"hs_twitterid,omitempty"`
	HsUniqueCreationKey                              string  `json:"hs_unique_creation_key,omitempty"`
	HsUpdatedByUserId                                string  `json:"hs_updated_by_user_id,omitempty"`
	HsUserIdsOfAllNotificationFollowers              string  `json:"hs_user_ids_of_all_notification_followers,omitempty"`
	HsUserIdsOfAllNotificationUnfollowers            string  `json:"hs_user_ids_of_all_notification_unfollowers,omitempty"`
	HsUserIdsOfAllOwners                             string  `json:"hs_user_ids_of_all_owners,omitempty"`
	HubspotOwnerAssigneddate                         string  `json:"hubspot_owner_assigneddate,omitempty"`
	IpCity                                           string  `json:"ip_city,omitempty"`
	IpCountry                                        string  `json:"ip_country,omitempty"`
	IpCountryCode                                    string  `json:"ip_country_code,omitempty"`
	IpLatlon                                         string  `json:"ip_latlon,omitempty"`
	IpState                                          string  `json:"ip_state,omitempty"`
	IpStateCode                                      string  `json:"ip_state_code,omitempty"`
	IpZipcode                                        string  `json:"ip_zipcode,omitempty"`
	JobFunction                                      string  `json:"job_function,omitempty"`
	Lastmodifieddate                                 string  `json:"lastmodifieddate,omitempty"`
	MaritalStatus                                    string  `json:"marital_status,omitempty"`
	MilitaryStatus                                   string  `json:"military_status,omitempty"`
	NumAssociatedDeals                               int64   `json:"num_associated_deals,omitempty"`
	NumConversionEvents                              int64   `json:"num_conversion_events,omitempty"`
	NumUniqueConversionEvents                        int64   `json:"num_unique_conversion_events,omitempty"`
	RecentConversionDate                             string  `json:"recent_conversion_date,omitempty"`
	RecentConversionEventName                        string  `json:"recent_conversion_event_name,omitempty"`
	RecentDealAmount                                 float64 `json:"recent_deal_amount,omitempty"`
	RecentDealCloseDate                              string  `json:"recent_deal_close_date,omitempty"`
	RelationshipStatus                               string  `json:"relationship_status,omitempty"`
	School                                           string  `json:"school,omitempty"`
	Seniority                                        string  `json:"seniority,omitempty"`
	StartDate                                        string  `json:"start_date,omitempty"`
	TotalRevenue                                     int64   `json:"total_revenue,omitempty"`
	WorkEmail                                        string  `json:"work_email,omitempty"`
	FirstName                                        string  `json:"firstname,omitempty"`
	HsAnalyticsFirstUrl                              string  `json:"hs_analytics_first_url,omitempty"`
	HsEmailDelivered                                 int64   `json:"hs_email_delivered,omitempty"`
	Twitterhandle                                    string  `json:"twitterhandle,omitempty"`
	Currentlyinworkflow                              string  `json:"currentlyinworkflow,omitempty"`
	Followercount                                    int64   `json:"followercount,omitempty"`
	HsAnalyticsLastUrl                               string  `json:"hs_analytics_last_url,omitempty"`
	HsEmailOpen                                      int64   `json:"hs_email_open,omitempty"`
	LastName                                         string  `json:"lastname,omitempty"`
	HsAnalyticsNumPageViews                          int64   `json:"hs_analytics_num_page_views,omitempty"`
	HsEmailClick                                     int64   `json:"hs_email_click,omitempty"`
	Salutation                                       string  `json:"salutation,omitempty"`
	Twitterprofilephoto                              string  `json:"twitterprofilephoto,omitempty"`
	Email                                            string  `json:"email,omitempty"`
	HsAnalyticsNumVisits                             int64   `json:"hs_analytics_num_visits,omitempty"`
	HsEmailBounce                                    int64   `json:"hs_email_bounce,omitempty"`
	HsPersona                                        string  `json:"hs_persona,omitempty"`
	HsSocialLastEngagement                           string  `json:"hs_social_last_engagement,omitempty"`
	HsAnalyticsNumEventCompletions                   int64   `json:"hs_analytics_num_event_completions,omitempty"`
	HsEmailOptout                                    bool    `json:"hs_email_optout,omitempty"`
	HsSocialTwitterClicks                            int64   `json:"hs_social_twitter_clicks,omitempty"`
	Mobilephone                                      string  `json:"mobilephone,omitempty"`
	Phone                                            string  `json:"phone,omitempty"`
	Fax                                              string  `json:"fax,omitempty"`
	HsAnalyticsFirstTimestamp                        string  `json:"hs_analytics_first_timestamp,omitempty"`
	HsEmailLastEmailName                             string  `json:"hs_email_last_email_name,omitempty"`
	HsEmailLastSendDate                              string  `json:"hs_email_last_send_date,omitempty"`
	HsSocialFacebookClicks                           int64   `json:"hs_social_facebook_clicks,omitempty"`
	Address                                          string  `json:"address,omitempty"`
	EngagementsLastMeetingBooked                     string  `json:"engagements_last_meeting_booked,omitempty"`
	EngagementsLastMeetingBookedCampaign             string  `json:"engagements_last_meeting_booked_campaign,omitempty"`
	EngagementsLastMeetingBookedMedium               string  `json:"engagements_last_meeting_booked_medium,omitempty"`
	EngagementsLastMeetingBookedSource               string  `json:"engagements_last_meeting_booked_source,omitempty"`
	HsAnalyticsFirstVisitTimestamp                   string  `json:"hs_analytics_first_visit_timestamp,omitempty"`
	HsEmailLastOpenDate                              string  `json:"hs_email_last_open_date,omitempty"`
	HsLatestMeetingActivity                          string  `json:"hs_latest_meeting_activity,omitempty"`
	HsSalesEmailLastReplied                          string  `json:"hs_sales_email_last_replied,omitempty"`
	HsSocialLinkedinClicks                           int64   `json:"hs_social_linkedin_clicks,omitempty"`
	HubspotOwnerId                                   string  `json:"hubspot_owner_id,omitempty"`
	NotesLastContacted                               string  `json:"notes_last_contacted,omitempty"`
	NotesLastUpdated                                 string  `json:"notes_last_updated,omitempty"`
	NotesNextActivityDate                            string  `json:"notes_next_activity_date,omitempty"`
	NumContactedNotes                                int64   `json:"num_contacted_notes,omitempty"`
	NumNotes                                         int64   `json:"num_notes,omitempty"`
	Owneremail                                       string  `json:"owneremail,omitempty"`
	Ownername                                        string  `json:"ownername,omitempty"`
	Surveymonkeyeventlastupdated                     int64   `json:"surveymonkeyeventlastupdated,omitempty"`
	Webinareventlastupdated                          int64   `json:"webinareventlastupdated,omitempty"`
	City                                             string  `json:"city,omitempty"`
	HsAnalyticsLastTimestamp                         string  `json:"hs_analytics_last_timestamp,omitempty"`
	HsEmailLastClickDate                             string  `json:"hs_email_last_click_date,omitempty"`
	HsSocialGooglePlusClicks                         int64   `json:"hs_social_google_plus_clicks,omitempty"`
	HubspotTeamId                                    string  `json:"hubspot_team_id,omitempty"`
	Linkedinbio                                      string  `json:"linkedinbio,omitempty"`
	Twitterbio                                       string  `json:"twitterbio,omitempty"`
	HsAllOwnerIds                                    string  `json:"hs_all_owner_ids,omitempty"`
	HsAnalyticsLastVisitTimestamp                    string  `json:"hs_analytics_last_visit_timestamp,omitempty"`
	HsEmailFirstSendDate                             string  `json:"hs_email_first_send_date,omitempty"`
	HsSocialNumBroadcastClicks                       int64   `json:"hs_social_num_broadcast_clicks,omitempty"`
	State                                            string  `json:"state,omitempty"`
	HsAllTeamIds                                     string  `json:"hs_all_team_ids,omitempty"`
	HsAnalyticsSource                                string  `json:"hs_analytics_source,omitempty"`
	HsEmailFirstOpenDate                             string  `json:"hs_email_first_open_date,omitempty"`
	HsLatestSource                                   string  `json:"hs_latest_source,omitempty"`
	Zip                                              string  `json:"zip,omitempty"`
	Country                                          string  `json:"country,omitempty"`
	HsAllAccessibleTeamIds                           string  `json:"hs_all_accessible_team_ids,omitempty"`
	HsAnalyticsSourceData1                           string  `json:"hs_analytics_source_data_1,omitempty"`
	HsEmailFirstClickDate                            string  `json:"hs_email_first_click_date,omitempty"`
	HsLatestSourceData1                              string  `json:"hs_latest_source_data_1,omitempty"`
	Linkedinconnections                              int64   `json:"linkedinconnections,omitempty"`
	HsAnalyticsSourceData2                           string  `json:"hs_analytics_source_data_2,omitempty"`
	HsEmailIsIneligible                              bool    `json:"hs_email_is_ineligible,omitempty"`
	HsLanguage                                       string  `json:"hs_language,omitempty"`
	HsLatestSourceData2                              string  `json:"hs_latest_source_data_2,omitempty"`
	Kloutscoregeneral                                int64   `json:"kloutscoregeneral,omitempty"`
	HsAnalyticsFirstReferrer                         string  `json:"hs_analytics_first_referrer,omitempty"`
	HsEmailFirstReplyDate                            string  `json:"hs_email_first_reply_date,omitempty"`
	Jobtitle                                         string  `json:"jobtitle,omitempty"`
	Photo                                            string  `json:"photo,omitempty"`
	HsAnalyticsLastReferrer                          string  `json:"hs_analytics_last_referrer,omitempty"`
	HsEmailLastReplyDate                             string  `json:"hs_email_last_reply_date,omitempty"`
	Message                                          string  `json:"message,omitempty"`
	Closedate                                        string  `json:"closedate,omitempty"`
	HsAnalyticsAveragePageViews                      int64   `json:"hs_analytics_average_page_views,omitempty"`
	HsEmailReplied                                   int64   `json:"hs_email_replied,omitempty"`
	HsAnalyticsRevenue                               int64   `json:"hs_analytics_revenue,omitempty"`
	HsLifecyclestageLeadDate                         string  `json:"hs_lifecyclestage_lead_date,omitempty"`
	HsLifecyclestageMarketingqualifiedleadDate       string  `json:"hs_lifecyclestage_marketingqualifiedlead_date,omitempty"`
	HsLifecyclestageOpportunityDate                  string  `json:"hs_lifecyclestage_opportunity_date,omitempty"`
	Lifecyclestage                                   string  `json:"lifecyclestage,omitempty"`
	HsLifecyclestageSalesqualifiedleadDate           string  `json:"hs_lifecyclestage_salesqualifiedlead_date,omitempty"`
	Createdate                                       string  `json:"createdate,omitempty"`
	HsLifecyclestageEvangelistDate                   string  `json:"hs_lifecyclestage_evangelist_date,omitempty"`
	HsLifecyclestageCustomerDate                     string  `json:"hs_lifecyclestage_customer_date,omitempty"`
	Hubspotscore                                     int64   `json:"hubspotscore,omitempty"`
	Company                                          string  `json:"company,omitempty"`
	HsLifecyclestageSubscriberDate                   string  `json:"hs_lifecyclestage_subscriber_date,omitempty"`
	HsLifecyclestageOtherDate                        string  `json:"hs_lifecyclestage_other_date,omitempty"`
	Website                                          string  `json:"website,omitempty"`
	Numemployees                                     string  `json:"numemployees,omitempty"`
	Annualrevenue                                    string  `json:"annualrevenue,omitempty"`
	Industry                                         string  `json:"industry,omitempty"`
	Associatedcompanyid                              int64   `json:"associatedcompanyid,omitempty"`
	Associatedcompanylastupdated                     int64   `json:"associatedcompanylastupdated,omitempty"`
	HsPredictivecontactscorebucket                   string  `json:"hs_predictivecontactscorebucket,omitempty"`
	HsPredictivecontactscore                         int64   `json:"hs_predictivecontactscore,omitempty"`
}