package crm

type ContactProperties struct {
	CompanySize                                      string  `json:"company_size"`
	DateOfBirth                                      string  `json:"date_of_birth"`
	DaysToClose                                      int64   `json:"days_to_close"`
	Degree                                           string  `json:"degree"`
	FieldOfStudy                                     string  `json:"field_of_study"`
	FirstConversionDate                              string  `json:"first_conversion_date"`
	FirstConversionEventName                         string  `json:"first_conversion_event_name"`
	FirstDealCreatedDate                             string  `json:"first_deal_created_date"`
	Gender                                           string  `json:"gender"`
	GraduationDate                                   string  `json:"graduation_date"`
	HsAdditionalEmails                               string  `json:"hs_additional_emails"`
	HsAllAssignedBusinessUnitIds                     string  `json:"hs_all_assigned_business_unit_ids"`
	HsAllContactVids                                 string  `json:"hs_all_contact_vids"`
	HsAnalyticsFirstTouchConvertingCampaign          string  `json:"hs_analytics_first_touch_converting_campaign"`
	HsAnalyticsLastTouchConvertingCampaign           string  `json:"hs_analytics_last_touch_converting_campaign"`
	HsAvatarFilemanagerKey                           string  `json:"hs_avatar_filemanager_key"`
	HsBuyingRole                                     string  `json:"hs_buying_role"`
	HsCalculatedFormSubmissions                      string  `json:"hs_calculated_form_submissions"`
	HsCalculatedMergedVids                           string  `json:"hs_calculated_merged_vids"`
	HsCalculatedMobileNumber                         string  `json:"hs_calculated_mobile_number"`
	HsCalculatedPhoneNumber                          string  `json:"hs_calculated_phone_number"`
	HsCalculatedPhoneNumberAreaCode                  string  `json:"hs_calculated_phone_number_area_code"`
	HsCalculatedPhoneNumberCountryCode               string  `json:"hs_calculated_phone_number_country_code"`
	HsCalculatedPhoneNumberRegionCode                string  `json:"hs_calculated_phone_number_region_code"`
	HsContentMembershipEmailConfirmed                bool    `json:"hs_content_membership_email_confirmed"`
	HsContentMembershipNotes                         string  `json:"hs_content_membership_notes"`
	HsContentMembershipRegisteredAt                  string  `json:"hs_content_membership_registered_at"`
	HsContentMembershipRegistrationDomainSentTo      string  `json:"hs_content_membership_registration_domain_sent_to"`
	HsContentMembershipRegistrationEmailSentAt       string  `json:"hs_content_membership_registration_email_sent_at"`
	HsContentMembershipStatus                        string  `json:"hs_content_membership_status"`
	HsConversationsVisitorEmail                      string  `json:"hs_conversations_visitor_email"`
	HsCountIsUnworked                                int64   `json:"hs_count_is_unworked"`
	HsCountIsWorked                                  int64   `json:"hs_count_is_worked"`
	HsCreatedByConversations                         bool    `json:"hs_created_by_conversations"`
	HsCreatedByUserId                                string  `json:"hs_created_by_user_id"`
	HsCreatedate                                     string  `json:"hs_createdate"`
	HsDateEnteredCustomer                            string  `json:"hs_date_entered_customer"`
	HsDateEnteredEvangelist                          string  `json:"hs_date_entered_evangelist"`
	HsDateEnteredLead                                string  `json:"hs_date_entered_lead"`
	HsDateEnteredMarketingqualifiedlead              string  `json:"hs_date_entered_marketingqualifiedlead"`
	HsDateEnteredOpportunity                         string  `json:"hs_date_entered_opportunity"`
	HsDateEnteredOther                               string  `json:"hs_date_entered_other"`
	HsDateEnteredSalesqualifiedlead                  string  `json:"hs_date_entered_salesqualifiedlead"`
	HsDateEnteredSubscriber                          string  `json:"hs_date_entered_subscriber"`
	HsDateExitedCustomer                             string  `json:"hs_date_exited_customer"`
	HsDateExitedEvangelist                           string  `json:"hs_date_exited_evangelist"`
	HsDateExitedLead                                 string  `json:"hs_date_exited_lead"`
	HsDateExitedMarketingqualifiedlead               string  `json:"hs_date_exited_marketingqualifiedlead"`
	HsDateExitedOpportunity                          string  `json:"hs_date_exited_opportunity"`
	HsDateExitedOther                                string  `json:"hs_date_exited_other"`
	HsDateExitedSalesqualifiedlead                   string  `json:"hs_date_exited_salesqualifiedlead"`
	HsDateExitedSubscriber                           string  `json:"hs_date_exited_subscriber"`
	HsDocumentLastRevisited                          string  `json:"hs_document_last_revisited"`
	HsEmailBadAddress                                bool    `json:"hs_email_bad_address"`
	HsEmailCustomerQuarantinedReason                 string  `json:"hs_email_customer_quarantined_reason"`
	HsEmailDomain                                    string  `json:"hs_email_domain"`
	HsEmailHardBounceReason                          string  `json:"hs_email_hard_bounce_reason"`
	HsEmailHardBounceReasonEnum                      string  `json:"hs_email_hard_bounce_reason_enum"`
	HsEmailQuarantined                               bool    `json:"hs_email_quarantined"`
	HsEmailQuarantinedReason                         string  `json:"hs_email_quarantined_reason"`
	HsEmailRecipientFatigueRecoveryTime              string  `json:"hs_email_recipient_fatigue_recovery_time"`
	HsEmailSendsSinceLastEngagement                  int64   `json:"hs_email_sends_since_last_engagement"`
	HsEmailconfirmationstatus                        string  `json:"hs_emailconfirmationstatus"`
	HsFacebookAdClicked                              bool    `json:"hs_facebook_ad_clicked"`
	HsFacebookClickId                                string  `json:"hs_facebook_click_id"`
	HsFacebookid                                     string  `json:"hs_facebookid"`
	HsFeedbackLastNpsFollowUp                        string  `json:"hs_feedback_last_nps_follow_up"`
	HsFeedbackLastNpsRating                          string  `json:"hs_feedback_last_nps_rating"`
	HsFeedbackLastSurveyDate                         string  `json:"hs_feedback_last_survey_date"`
	HsFeedbackShowNpsWebSurvey                       bool    `json:"hs_feedback_show_nps_web_survey"`
	HsFirstEngagementObjectId                        string  `json:"hs_first_engagement_object_id"`
	HsFirstSubscriptionCreateDate                    string  `json:"hs_first_subscription_create_date"`
	HsGoogleClickId                                  string  `json:"hs_google_click_id"`
	HsGoogleplusid                                   string  `json:"hs_googleplusid"`
	HsHasActiveSubscription                          int64   `json:"hs_has_active_subscription"`
	HsIpTimezone                                     string  `json:"hs_ip_timezone"`
	HsIsContact                                      bool    `json:"hs_is_contact"`
	HsIsUnworked                                     bool    `json:"hs_is_unworked"`
	HsLastSalesActivityDate                          string  `json:"hs_last_sales_activity_date"`
	HsLastSalesActivityTimestamp                     string  `json:"hs_last_sales_activity_timestamp"`
	HsLastmodifieddate                               string  `json:"hs_lastmodifieddate"`
	HsLatestSequenceEndedDate                        string  `json:"hs_latest_sequence_ended_date"`
	HsLatestSequenceEnrolled                         int64   `json:"hs_latest_sequence_enrolled"`
	HsLatestSequenceEnrolledDate                     string  `json:"hs_latest_sequence_enrolled_date"`
	HsLatestSequenceFinishedDate                     string  `json:"hs_latest_sequence_finished_date"`
	HsLatestSequenceUnenrolledDate                   string  `json:"hs_latest_sequence_unenrolled_date"`
	HsLatestSourceTimestamp                          string  `json:"hs_latest_source_timestamp"`
	HsLatestSubscriptionCreateDate                   string  `json:"hs_latest_subscription_create_date"`
	HsLeadStatus                                     string  `json:"hs_lead_status"`
	HsLegalBasis                                     string  `json:"hs_legal_basis"`
	HsLinkedinid                                     string  `json:"hs_linkedinid"`
	HsMarketableReasonId                             string  `json:"hs_marketable_reason_id"`
	HsMarketableReasonType                           string  `json:"hs_marketable_reason_type"`
	HsMarketableStatus                               string  `json:"hs_marketable_status"`
	HsMarketableUntilRenewal                         string  `json:"hs_marketable_until_renewal"`
	HsMergedObjectIds                                string  `json:"hs_merged_object_ids"`
	HsObjectId                                       string  `json:"hs_object_id"`
	HsPipeline                                       string  `json:"hs_pipeline"`
	HsPredictivecontactscoreV2                       int64   `json:"hs_predictivecontactscore_v2"`
	HsPredictivescoringtier                          string  `json:"hs_predictivescoringtier"`
	HsSaFirstEngagementDate                          string  `json:"hs_sa_first_engagement_date"`
	HsSaFirstEngagementDescr                         string  `json:"hs_sa_first_engagement_descr"`
	HsSaFirstEngagementObjectType                    string  `json:"hs_sa_first_engagement_object_type"`
	HsSalesEmailLastClicked                          string  `json:"hs_sales_email_last_clicked"`
	HsSalesEmailLastOpened                           string  `json:"hs_sales_email_last_opened"`
	HsSearchableCalculatedInternationalMobileNumber  string  `json:"hs_searchable_calculated_international_mobile_number"`
	HsSearchableCalculatedInternationalPhoneNumber   string  `json:"hs_searchable_calculated_international_phone_number"`
	HsSearchableCalculatedMobileNumber               string  `json:"hs_searchable_calculated_mobile_number"`
	HsSearchableCalculatedPhoneNumber                string  `json:"hs_searchable_calculated_phone_number"`
	HsSequencesActivelyEnrolledCount                 int64   `json:"hs_sequences_actively_enrolled_count"`
	HsSequencesEnrolledCount                         int64   `json:"hs_sequences_enrolled_count"`
	HsSequencesIsEnrolled                            bool    `json:"hs_sequences_is_enrolled"`
	HsTestpurge                                      string  `json:"hs_testpurge"`
	HsTestrollback                                   string  `json:"hs_testrollback"`
	HsTimeBetweenContactCreationAndDealClose         int64   `json:"hs_time_between_contact_creation_and_deal_close"`
	HsTimeBetweenContactCreationAndDealCreation      int64   `json:"hs_time_between_contact_creation_and_deal_creation"`
	HsTimeInCustomer                                 int64   `json:"hs_time_in_customer"`
	HsTimeInEvangelist                               int64   `json:"hs_time_in_evangelist"`
	HsTimeInLead                                     int64   `json:"hs_time_in_lead"`
	HsTimeInMarketingqualifiedlead                   int64   `json:"hs_time_in_marketingqualifiedlead"`
	HsTimeInOpportunity                              int64   `json:"hs_time_in_opportunity"`
	HsTimeInOther                                    int64   `json:"hs_time_in_other"`
	HsTimeInSalesqualifiedlead                       int64   `json:"hs_time_in_salesqualifiedlead"`
	HsTimeInSubscriber                               int64   `json:"hs_time_in_subscriber"`
	HsTimeToFirstEngagement                          int64   `json:"hs_time_to_first_engagement"`
	HsTimeToMoveFromLeadToCustomer                   int64   `json:"hs_time_to_move_from_lead_to_customer"`
	HsTimeToMoveFromMarketingqualifiedleadToCustomer int64   `json:"hs_time_to_move_from_marketingqualifiedlead_to_customer"`
	HsTimeToMoveFromOpportunityToCustomer            int64   `json:"hs_time_to_move_from_opportunity_to_customer"`
	HsTimeToMoveFromSalesqualifiedleadToCustomer     int64   `json:"hs_time_to_move_from_salesqualifiedlead_to_customer"`
	HsTimeToMoveFromSubscriberToCustomer             int64   `json:"hs_time_to_move_from_subscriber_to_customer"`
	HsTimezone                                       string  `json:"hs_timezone"`
	HsTwitterid                                      string  `json:"hs_twitterid"`
	HsUniqueCreationKey                              string  `json:"hs_unique_creation_key"`
	HsUpdatedByUserId                                string  `json:"hs_updated_by_user_id"`
	HsUserIdsOfAllNotificationFollowers              string  `json:"hs_user_ids_of_all_notification_followers"`
	HsUserIdsOfAllNotificationUnfollowers            string  `json:"hs_user_ids_of_all_notification_unfollowers"`
	HsUserIdsOfAllOwners                             string  `json:"hs_user_ids_of_all_owners"`
	HubspotOwnerAssigneddate                         string  `json:"hubspot_owner_assigneddate"`
	IpCity                                           string  `json:"ip_city"`
	IpCountry                                        string  `json:"ip_country"`
	IpCountryCode                                    string  `json:"ip_country_code"`
	IpLatlon                                         string  `json:"ip_latlon"`
	IpState                                          string  `json:"ip_state"`
	IpStateCode                                      string  `json:"ip_state_code"`
	IpZipcode                                        string  `json:"ip_zipcode"`
	JobFunction                                      string  `json:"job_function"`
	Lastmodifieddate                                 string  `json:"lastmodifieddate"`
	MaritalStatus                                    string  `json:"marital_status"`
	MilitaryStatus                                   string  `json:"military_status"`
	NumAssociatedDeals                               int64   `json:"num_associated_deals"`
	NumConversionEvents                              int64   `json:"num_conversion_events"`
	NumUniqueConversionEvents                        int64   `json:"num_unique_conversion_events"`
	RecentConversionDate                             string  `json:"recent_conversion_date"`
	RecentConversionEventName                        string  `json:"recent_conversion_event_name"`
	RecentDealAmount                                 float64 `json:"recent_deal_amount"`
	RecentDealCloseDate                              string  `json:"recent_deal_close_date"`
	RelationshipStatus                               string  `json:"relationship_status"`
	School                                           string  `json:"school"`
	Seniority                                        string  `json:"seniority"`
	StartDate                                        string  `json:"start_date"`
	TotalRevenue                                     int64   `json:"total_revenue"`
	WorkEmail                                        string  `json:"work_email"`
	Firstname                                        string  `json:"firstname"`
	HsAnalyticsFirstUrl                              string  `json:"hs_analytics_first_url"`
	HsEmailDelivered                                 int64   `json:"hs_email_delivered"`
	Twitterhandle                                    string  `json:"twitterhandle"`
	Currentlyinworkflow                              string  `json:"currentlyinworkflow"`
	Followercount                                    int64   `json:"followercount"`
	HsAnalyticsLastUrl                               string  `json:"hs_analytics_last_url"`
	HsEmailOpen                                      int64   `json:"hs_email_open"`
	Lastname                                         string  `json:"lastname"`
	HsAnalyticsNumPageViews                          int64   `json:"hs_analytics_num_page_views"`
	HsEmailClick                                     int64   `json:"hs_email_click"`
	Salutation                                       string  `json:"salutation"`
	Twitterprofilephoto                              string  `json:"twitterprofilephoto"`
	Email                                            string  `json:"email"`
	HsAnalyticsNumVisits                             int64   `json:"hs_analytics_num_visits"`
	HsEmailBounce                                    int64   `json:"hs_email_bounce"`
	HsPersona                                        string  `json:"hs_persona"`
	HsSocialLastEngagement                           string  `json:"hs_social_last_engagement"`
	HsAnalyticsNumEventCompletions                   int64   `json:"hs_analytics_num_event_completions"`
	HsEmailOptout                                    bool    `json:"hs_email_optout"`
	HsSocialTwitterClicks                            int64   `json:"hs_social_twitter_clicks"`
	Mobilephone                                      string  `json:"mobilephone"`
	Phone                                            string  `json:"phone"`
	Fax                                              string  `json:"fax"`
	HsAnalyticsFirstTimestamp                        string  `json:"hs_analytics_first_timestamp"`
	HsEmailLastEmailName                             string  `json:"hs_email_last_email_name"`
	HsEmailLastSendDate                              string  `json:"hs_email_last_send_date"`
	HsSocialFacebookClicks                           int64   `json:"hs_social_facebook_clicks"`
	Address                                          string  `json:"address"`
	EngagementsLastMeetingBooked                     string  `json:"engagements_last_meeting_booked"`
	EngagementsLastMeetingBookedCampaign             string  `json:"engagements_last_meeting_booked_campaign"`
	EngagementsLastMeetingBookedMedium               string  `json:"engagements_last_meeting_booked_medium"`
	EngagementsLastMeetingBookedSource               string  `json:"engagements_last_meeting_booked_source"`
	HsAnalyticsFirstVisitTimestamp                   string  `json:"hs_analytics_first_visit_timestamp"`
	HsEmailLastOpenDate                              string  `json:"hs_email_last_open_date"`
	HsLatestMeetingActivity                          string  `json:"hs_latest_meeting_activity"`
	HsSalesEmailLastReplied                          string  `json:"hs_sales_email_last_replied"`
	HsSocialLinkedinClicks                           int64   `json:"hs_social_linkedin_clicks"`
	HubspotOwnerId                                   string  `json:"hubspot_owner_id"`
	NotesLastContacted                               string  `json:"notes_last_contacted"`
	NotesLastUpdated                                 string  `json:"notes_last_updated"`
	NotesNextActivityDate                            string  `json:"notes_next_activity_date"`
	NumContactedNotes                                int64   `json:"num_contacted_notes"`
	NumNotes                                         int64   `json:"num_notes"`
	Owneremail                                       string  `json:"owneremail"`
	Ownername                                        string  `json:"ownername"`
	Surveymonkeyeventlastupdated                     int64   `json:"surveymonkeyeventlastupdated"`
	Webinareventlastupdated                          int64   `json:"webinareventlastupdated"`
	City                                             string  `json:"city"`
	HsAnalyticsLastTimestamp                         string  `json:"hs_analytics_last_timestamp"`
	HsEmailLastClickDate                             string  `json:"hs_email_last_click_date"`
	HsSocialGooglePlusClicks                         int64   `json:"hs_social_google_plus_clicks"`
	HubspotTeamId                                    string  `json:"hubspot_team_id"`
	Linkedinbio                                      string  `json:"linkedinbio"`
	Twitterbio                                       string  `json:"twitterbio"`
	HsAllOwnerIds                                    string  `json:"hs_all_owner_ids"`
	HsAnalyticsLastVisitTimestamp                    string  `json:"hs_analytics_last_visit_timestamp"`
	HsEmailFirstSendDate                             string  `json:"hs_email_first_send_date"`
	HsSocialNumBroadcastClicks                       int64   `json:"hs_social_num_broadcast_clicks"`
	State                                            string  `json:"state"`
	HsAllTeamIds                                     string  `json:"hs_all_team_ids"`
	HsAnalyticsSource                                string  `json:"hs_analytics_source"`
	HsEmailFirstOpenDate                             string  `json:"hs_email_first_open_date"`
	HsLatestSource                                   string  `json:"hs_latest_source"`
	Zip                                              string  `json:"zip"`
	Country                                          string  `json:"country"`
	HsAllAccessibleTeamIds                           string  `json:"hs_all_accessible_team_ids"`
	HsAnalyticsSourceData1                           string  `json:"hs_analytics_source_data_1"`
	HsEmailFirstClickDate                            string  `json:"hs_email_first_click_date"`
	HsLatestSourceData1                              string  `json:"hs_latest_source_data_1"`
	Linkedinconnections                              int64   `json:"linkedinconnections"`
	HsAnalyticsSourceData2                           string  `json:"hs_analytics_source_data_2"`
	HsEmailIsIneligible                              bool    `json:"hs_email_is_ineligible"`
	HsLanguage                                       string  `json:"hs_language"`
	HsLatestSourceData2                              string  `json:"hs_latest_source_data_2"`
	Kloutscoregeneral                                int64   `json:"kloutscoregeneral"`
	HsAnalyticsFirstReferrer                         string  `json:"hs_analytics_first_referrer"`
	HsEmailFirstReplyDate                            string  `json:"hs_email_first_reply_date"`
	Jobtitle                                         string  `json:"jobtitle"`
	Photo                                            string  `json:"photo"`
	HsAnalyticsLastReferrer                          string  `json:"hs_analytics_last_referrer"`
	HsEmailLastReplyDate                             string  `json:"hs_email_last_reply_date"`
	Message                                          string  `json:"message"`
	Closedate                                        string  `json:"closedate"`
	HsAnalyticsAveragePageViews                      int64   `json:"hs_analytics_average_page_views"`
	HsEmailReplied                                   int64   `json:"hs_email_replied"`
	HsAnalyticsRevenue                               int64   `json:"hs_analytics_revenue"`
	HsLifecyclestageLeadDate                         string  `json:"hs_lifecyclestage_lead_date"`
	HsLifecyclestageMarketingqualifiedleadDate       string  `json:"hs_lifecyclestage_marketingqualifiedlead_date"`
	HsLifecyclestageOpportunityDate                  string  `json:"hs_lifecyclestage_opportunity_date"`
	Lifecyclestage                                   string  `json:"lifecyclestage"`
	HsLifecyclestageSalesqualifiedleadDate           string  `json:"hs_lifecyclestage_salesqualifiedlead_date"`
	Createdate                                       string  `json:"createdate"`
	HsLifecyclestageEvangelistDate                   string  `json:"hs_lifecyclestage_evangelist_date"`
	HsLifecyclestageCustomerDate                     string  `json:"hs_lifecyclestage_customer_date"`
	Hubspotscore                                     int64   `json:"hubspotscore"`
	Company                                          string  `json:"company"`
	HsLifecyclestageSubscriberDate                   string  `json:"hs_lifecyclestage_subscriber_date"`
	HsLifecyclestageOtherDate                        string  `json:"hs_lifecyclestage_other_date"`
	Website                                          string  `json:"website"`
	Numemployees                                     string  `json:"numemployees"`
	Annualrevenue                                    string  `json:"annualrevenue"`
	Industry                                         string  `json:"industry"`
	Associatedcompanyid                              int64   `json:"associatedcompanyid"`
	Associatedcompanylastupdated                     int64   `json:"associatedcompanylastupdated"`
	HsPredictivecontactscorebucket                   string  `json:"hs_predictivecontactscorebucket"`
	HsPredictivecontactscore                         int64   `json:"hs_predictivecontactscore"`
}