package crm

type LineItemProperties struct {
	Amount                                float64 `json:"amount"`
	Createdate                            string  `json:"createdate"`
	Description                           string  `json:"description"`
	Discount                              float64 `json:"discount"`
	HsAcv                                 int64   `json:"hs_acv"`
	HsAllAccessibleTeamIds                string  `json:"hs_all_accessible_team_ids"`
	HsAllAssignedBusinessUnitIds          string  `json:"hs_all_assigned_business_unit_ids"`
	HsAllOwnerIds                         string  `json:"hs_all_owner_ids"`
	HsAllTeamIds                          string  `json:"hs_all_team_ids"`
	HsAllowBuyerSelectedQuantity          string  `json:"hs_allow_buyer_selected_quantity"`
	HsArr                                 int64   `json:"hs_arr"`
	HsCostOfGoodsSold                     int64   `json:"hs_cost_of_goods_sold"`
	HsCreatedByUserId                     string  `json:"hs_created_by_user_id"`
	HsCreatedate                          string  `json:"hs_createdate"`
	HsDiscountPercentage                  float64 `json:"hs_discount_percentage"`
	HsExternalId                          string  `json:"hs_external_id"`
	HsImages                              string  `json:"hs_images"`
	HsLastmodifieddate                    string  `json:"hs_lastmodifieddate"`
	HsLineItemCurrencyCode                string  `json:"hs_line_item_currency_code"`
	HsMargin                              int64   `json:"hs_margin"`
	HsMarginAcv                           int64   `json:"hs_margin_acv"`
	HsMarginArr                           int64   `json:"hs_margin_arr"`
	HsMarginMrr                           int64   `json:"hs_margin_mrr"`
	HsMarginTcv                           int64   `json:"hs_margin_tcv"`
	HsMergedObjectIds                     string  `json:"hs_merged_object_ids"`
	HsMrr                                 int64   `json:"hs_mrr"`
	HsObjectId                            string  `json:"hs_object_id"`
	HsPositionOnQuote                     string  `json:"hs_position_on_quote"`
	HsPreDiscountAmount                   float64 `json:"hs_pre_discount_amount"`
	HsProductId                           string  `json:"hs_product_id"`
	HsRecurringBillingEndDate             string  `json:"hs_recurring_billing_end_date"`
	HsRecurringBillingNumberOfPayments    int64   `json:"hs_recurring_billing_int64_of_payments"`
	HsRecurringBillingPeriod              string  `json:"hs_recurring_billing_period"`
	HsRecurringBillingStartDate           string  `json:"hs_recurring_billing_start_date"`
	HsRecurringBillingTerms               string  `json:"hs_recurring_billing_terms"`
	HsSku                                 string  `json:"hs_sku"`
	HsSyncAmount                          int64   `json:"hs_sync_amount"`
	HsTcv                                 int64   `json:"hs_tcv"`
	HsTermInMonths                        int64   `json:"hs_term_in_months"`
	HsTotalDiscount                       float64 `json:"hs_total_discount"`
	HsUniqueCreationKey                   string  `json:"hs_unique_creation_key"`
	HsUpdatedByUserId                     string  `json:"hs_updated_by_user_id"`
	HsUrl                                 string  `json:"hs_url"`
	HsUserIdsOfAllNotificationFollowers   string  `json:"hs_user_ids_of_all_notification_followers"`
	HsUserIdsOfAllNotificationUnfollowers string  `json:"hs_user_ids_of_all_notification_unfollowers"`
	HsUserIdsOfAllOwners                  string  `json:"hs_user_ids_of_all_owners"`
	HsVariantId                           int64   `json:"hs_variant_id"`
	HubspotOwnerAssigneddate              string  `json:"hubspot_owner_assigneddate"`
	HubspotOwnerId                        string  `json:"hubspot_owner_id"`
	HubspotTeamId                         string  `json:"hubspot_team_id"`
	Name                                  string  `json:"name"`
	Price                                 float64 `json:"price"`
	Quantity                              int64   `json:"quantity"`
	Recurringbillingfrequency             string  `json:"recurringbillingfrequency"`
	Tax                                   float64 `json:"tax"`
}